// <auto-generated />
using System;
using System.Collections.Generic;
using Hatband.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hatband.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HatbandDbContext))]
    [Migration("20261006234256_UseComplexGameArtwork")]
    partial class UseComplexGameArtwork
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Hatband.Core.Models.CacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("CacheEntries", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Added")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InstallSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlaytimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortingName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Artwork", "Hatband.Core.Models.Games.Game.Artwork#GameArtwork", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("BackgroundImagePath")
                                .HasColumnType("TEXT")
                                .HasColumnName("Artwork_BackgroundImagePath");

                            b1.Property<string>("CoverImagePath")
                                .HasColumnType("TEXT")
                                .HasColumnName("Artwork_CoverImagePath");

                            b1.Property<string>("IconPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("Artwork_IconPath");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DefaultArtwork", "Hatband.Core.Models.Games.Game.DefaultArtwork#GameArtwork", b1 =>
                        {
                            b1.Property<string>("BackgroundImagePath")
                                .HasColumnType("TEXT")
                                .HasColumnName("DefaultArtwork_BackgroundImagePath");

                            b1.Property<string>("CoverImagePath")
                                .HasColumnType("TEXT")
                                .HasColumnName("DefaultArtwork_CoverImagePath");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("IconPath")
                                .HasColumnType("TEXT")
                                .HasColumnName("DefaultArtwork_IconPath");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("GameArtwork");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GameLibraryId");

                    b.HasIndex("SourceId", "SourceGameId")
                        .IsUnique();

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.Games.GameAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameActions", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.Libraries.GameLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.Games.Game", b =>
                {
                    b.HasOne("Hatband.Core.Models.Libraries.GameLibrary", null)
                        .WithMany("Games")
                        .HasForeignKey("GameLibraryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Hatband.Core.Models.Compatibility.CompatibilityLayer", "CompatibilityLayer", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Tier")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CompatibilityLayer_Tier");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsOne("Hatband.Core.Models.Games.CompatibilityTool", "Tool", b2 =>
                                {
                                    b2.Property<Guid>("CompatibilityLayerGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("InstallationPath")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CompatibilityTool_InstallationPath");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CompatibilityTool_Name");

                                    b2.Property<int>("Source")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("CompatibilityTool_Source");

                                    b2.Property<string>("Version")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CompatibilityTool_Version");

                                    b2.HasKey("CompatibilityLayerGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("CompatibilityLayerGameId");
                                });

                            b1.OwnsOne("Hatband.Core.Models.Games.GameCompatibilityPrefix", "Prefix", b2 =>
                                {
                                    b2.Property<Guid>("CompatibilityLayerGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("IsManaged")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("CompatibilityPrefix_IsManaged");

                                    b2.Property<string>("Path")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CompatibilityPrefix_Path");

                                    b2.HasKey("CompatibilityLayerGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("CompatibilityLayerGameId");
                                });

                            b1.Navigation("Prefix");

                            b1.Navigation("Tool");
                        });

                    b.OwnsOne("Hatband.Core.Models.Games.GameInstallationInfo", "InstallationInfo", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("InstallDirectory")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("InstallationInfo_InstallDirectory");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("Hatband.Core.Models.Games.GameMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_Description");

                            b1.Property<string>("Developer")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_Developer");

                            b1.Property<string>("Genre")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_Genre");

                            b1.Property<string>("LanguageTag")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_LanguageTag");

                            b1.Property<int?>("NativePlatforms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Metadata_NativePlatforms");

                            b1.Property<string>("Publisher")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_Publisher");

                            b1.Property<DateOnly?>("ReleaseDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_ReleaseDate");

                            b1.Property<string>("StoreGameId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_StoreGameId");

                            b1.Property<string>("StoreName")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_StoreName");

                            b1.Property<string>("StoreSourceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_StoreSourceId");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsOne("Hatband.Core.Models.Games.GameTimeToBeat", "TimeToBeat", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("CompletionistSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_CompletionistSeconds");

                            b1.Property<int?>("HowLongToBeatGameId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_GameId");

                            b1.Property<string>("HowLongToBeatName")
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeToBeat_GameName");

                            b1.Property<long?>("MainStoryPlusExtrasSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_MainStoryPlusExtrasSeconds");

                            b1.Property<long?>("MainStorySeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_MainStorySeconds");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("CompatibilityLayer");

                    b.Navigation("InstallationInfo");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("TimeToBeat");
                });

            modelBuilder.Entity("Hatband.Core.Models.Games.GameAction", b =>
                {
                    b.HasOne("Hatband.Core.Models.Games.Game", null)
                        .WithMany("GameActions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hatband.Core.Models.Games.Game", b =>
                {
                    b.Navigation("GameActions");
                });

            modelBuilder.Entity("Hatband.Core.Models.Libraries.GameLibrary", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
