// <auto-generated />
using System;
using Hatband.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hatband.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HatbandDbContext))]
    partial class HatbandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Hatband.Core.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Added")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameLibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InstallSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNameCustomized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlaytimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortingName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceGameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameLibraryId");

                    b.HasIndex("SourceId", "SourceGameId")
                        .IsUnique();

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.GameLaunchAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameLaunchActions", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.GameLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("Hatband.Core.Models.Game", b =>
                {
                    b.HasOne("Hatband.Core.Models.GameLibrary", null)
                        .WithMany("Games")
                        .HasForeignKey("GameLibraryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Hatband.Core.Models.GameMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Developer")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Genre")
                                .HasColumnType("TEXT")
                                .HasColumnName("Genre");

                            b1.Property<string>("LanguageTag")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_LanguageTag");

                            b1.Property<int?>("NativePlatforms")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Metadata_NativePlatforms");

                            b1.Property<string>("Publisher")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly?>("ReleaseDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("StoreName")
                                .HasColumnType("TEXT")
                                .HasColumnName("Metadata_StoreName");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsOne("Hatband.Core.Models.GameArtwork", "Artwork", b2 =>
                                {
                                    b2.Property<Guid>("GameMetadataGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("BackgroundImagePath")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CoverImagePath")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("IconPath")
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("IsBackgroundCustomized")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Artwork_IsBackgroundCustomized");

                                    b2.Property<bool>("IsCoverCustomized")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Artwork_IsCoverCustomized");

                                    b2.Property<bool>("IsIconCustomized")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Artwork_IsIconCustomized");

                                    b2.HasKey("GameMetadataGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("GameMetadataGameId");
                                });

                            b1.OwnsOne("Hatband.Core.Models.GameMetadataOverrides", "Overrides", b2 =>
                                {
                                    b2.Property<Guid>("GameMetadataGameId")
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("Description")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Overrides_Description");

                                    b2.Property<bool>("Developer")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Overrides_Developer");

                                    b2.Property<bool>("Genre")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Overrides_Genre");

                                    b2.Property<bool>("Publisher")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Overrides_Publisher");

                                    b2.Property<bool>("ReleaseDate")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasDefaultValue(false)
                                        .HasColumnName("Metadata_Overrides_ReleaseDate");

                                    b2.HasKey("GameMetadataGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("GameMetadataGameId");
                                });

                            b1.Navigation("Artwork")
                                .IsRequired();

                            b1.Navigation("Overrides")
                                .IsRequired();
                        });

                    b.OwnsOne("Hatband.Core.Models.GameTimeToBeat", "TimeToBeat", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("TEXT");

                            b1.Property<long?>("CompletionistSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_CompletionistSeconds");

                            b1.Property<int?>("HowLongToBeatGameId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_GameId");

                            b1.Property<string>("HowLongToBeatName")
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeToBeat_GameName");

                            b1.Property<DateTime?>("LastSearchedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeToBeat_LastSearchedAtUtc");

                            b1.Property<long?>("MainStoryPlusExtrasSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_MainStoryPlusExtrasSeconds");

                            b1.Property<long?>("MainStorySeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TimeToBeat_MainStorySeconds");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("TimeToBeat");
                });

            modelBuilder.Entity("Hatband.Core.Models.GameLaunchAction", b =>
                {
                    b.HasOne("Hatband.Core.Models.Game", null)
                        .WithMany("LaunchActions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hatband.Core.Models.Game", b =>
                {
                    b.Navigation("LaunchActions");
                });

            modelBuilder.Entity("Hatband.Core.Models.GameLibrary", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
